[package]
name = "mutate_level"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
serde_json = "1.0.69"
fastrand = "1.5.0"
rayon = "1.5.1"